### ISSUE TITLE
New Business Rule Required

### ISSUE THREAD

**Issue by lemendoza** [ceorellana/ISII-WORKSHOPS-EDUCACION_CONTINUA#4]
**Is your feature request related to a problem? Please describe.**
This feature is not related to a problem. It is related to a new policy of the organization.
Based on the impact of the pandemic in the 2020 results, the board of the company has approved a new business rule (policy) beginning january 2021, that needs to be included in our product.

**Describe the solution you'd like**
The new business rule establishes: If the customer is male, over 25 and younger than 45 then it is needed to subtract $100 from the base premium.
Therefore, we ask you to modify the premium calculation adding this new rule.

**Describe alternatives you've considered**
There is no alternative to be considered.

**Additional context**
I will provide you with more information if needed.

Best regards,
LEMM

**Comment by ceorellana** [comment]
We have proceeded with categorizing the issue. We will now proceed to process the request, @ejgomez95 will be the assigned analyst and develop a solution, and @ceorellana will perform the tests.

**Comment by ejgomez95** [comment]
Does the client @lemendoza agree with the following impact analysis? In order to solve the request we will make use of the programmer's computer which, in this, case will be my computer aka @ejgomez95. The software requerimients are as follows: IDE will be Eclipse 2020-09 R. the build tool will be Gradle, and the tests will be performed by using JUnit.  In order to add the new business rule we will modify the source code and insert a new if statement within the method that calculates the base premium, it will include the specified parameters: "If the customer is male, over 25 and younger than 45" and the expected result of subtracting $100 from the base premium. The allocated time for this changes is approximately 5-10 minutes, To the tester @ceorellana the program might show different results than the ones than we have previously tested if the paramaters specified above are met.

**Comment by lemendoza** [comment]
I agree. Proceed.

**Comment by ejgomez95** [comment]
https://github.com/ceorellana/ISII-WORKSHOPS-EDUCACION_CONTINUA/blob/ab7a014328c9e4009bd0b2e0794269a13fd127d0/ec.edu.espol.workshops.second/src/main/java/ec/edu/espol/workshops/second/CarInsurance.java#L76-L78

**Comment by ceorellana** [comment]
The attached Structural Testing Plan was executed and pass regarding the addition of the new requirement. We will soon proceed with the acceptance testing.
[Structural Testing Plan.pdf](https://github.com/ceorellana/ISII-WORKSHOPS-EDUCACION_CONTINUA/files/5845582/Structural.Testing.Plan.pdf)

**Comment by ceorellana** [comment]
Does the client @lemendoza  agree with the attached Acceptance Testing Plan?

[Acceptance Testing Plan.pdf](https://github.com/ceorellana/ISII-WORKSHOPS-EDUCACION_CONTINUA/files/5845736/Acceptance.Testing.Plan.pdf)

**Comment by lemendoza** [comment]
Yes, I agree. Please continue.

**Comment by ceorellana** [comment]
> Yes, I agree. Please continue.

Understood, @lemendoza you may now proceed to execute the test cases defined in the aforementioned Testing Plan and verify if they pass.

**Comment by ejgomez95** [comment]
> Yes, I agree. Please continue.

Understood, @lemendoza in order to use the new version of the code you can find it under the code section in where you can clone the repository, if you don't possess a previous version of the code; if you have a previous version of the code ignore this step. You should be able to move to the branch IssuesManagement by using the command "git checkout IssuesManagement" inside the folder where the code is located, and make sure you open Eclipse IDE once you are in this branch, else the code won't show the new requeriment change. Alternatively you can change into the IssuesManagement branch by right clicking in the folder containing the proyect, hovering under the option Team, hovering under the option Switch to, and selecting the option Other, after that you should be able to select the IssuesManagement branch, however by doing this you might need to restart the IDE to make sure the code loads properly. Once you are ready you may proceed to execute the test cases definied in the aforementioned Testing Plan and verify if they pass.

**Comment by ceorellana** [comment]
> Yes, I agree. Please continue.

Understood. @lemendoza you can now execute the tests on the Testing Plan and verify if they pass. Each test indicates the input value that you need to assign.

**Comment by lemendoza** [comment]
Please, perform the tests and let me know the results.

**Comment by ceorellana** [comment]
The tests have passed successfully. @lemendoza do you accept the solution developed?

**Comment by lemendoza** [comment]
Yes, I accept.

**Comment by ceorellana** [comment]
Understood. With this, I inform you @lemendoza  that the solution has been completed and @ejgomez95  will release a new version for you

**Comment by lemendoza** [comment]
Ok.

**Comment by ejgomez95** [comment]
A new version of the code has been released @lemendoza in order to use the new version of the code you should be able to move to the branch IssuesManagement by using the command "git checkout IssuesManagement" inside the folder where the code is located, after that open Eclipse IDE and you can proceed to use the new code. Alternatively you can change into the IssuesManagement branch directly from the Eclipse IDE by right clicking in the folder containing the proyect, hovering under the option Team, hovering under the option Switch to, and selecting the option Other, after that you should be able to select the IssuesManagement branch, however by doing this you might need to restart the IDE to make sure the code loads properly, after this operation you can proceed to test the new code.

**Comment by ceorellana** [comment]
@lemendoza were you able to use the new release of the system? If, are you satisfied with the solution provided?

**Comment by lemendoza** [comment]
Yes, and I satisfied with the solution.
